#ifndef _GSM_48_H_
#define _GSM_48_H_

/* GSM 04.08 4.1.2.1 */
#define GSM48_MM_ST_NULL        0
#define GSM48_MM_ST_LOC_UPD_INIT    3
#define GSM48_MM_ST_WAIT_OUT_MM_CONN    5
#define GSM48_MM_ST_MM_CONN_ACTIVE  6
#define GSM48_MM_ST_IMSI_DETACH_INIT    7
#define GSM48_MM_ST_PROCESS_CM_SERV_P   8
#define GSM48_MM_ST_WAIT_NETWORK_CMD    9
#define GSM48_MM_ST_LOC_UPD_REJ     10
#define GSM48_MM_ST_WAIT_RR_CONN_LUPD   13
#define GSM48_MM_ST_WAIT_RR_CONN_MM_CON 14
#define GSM48_MM_ST_WAIT_RR_CONN_IMSI_D 15
#define GSM48_MM_ST_WAIT_REEST      17
#define GSM48_MM_ST_WAIT_RR_ACTIVE  18
#define GSM48_MM_ST_MM_IDLE     19
#define GSM48_MM_ST_WAIT_ADD_OUT_MM_CON 20
#define GSM48_MM_ST_MM_CONN_ACTIVE_VGCS 21
#define GSM48_MM_ST_WAIT_RR_CONN_VGCS   22
#define GSM48_MM_ST_LOC_UPD_PEND    23
#define GSM48_MM_ST_IMSI_DETACH_PEND    24
#define GSM48_MM_ST_RR_CONN_RELEASE_NA  25

/* GSM 04.08 4.1.2.1 */
#define GSM48_MM_SST_NORMAL_SERVICE 1
#define GSM48_MM_SST_ATTEMPT_UPDATE 2
#define GSM48_MM_SST_LIMITED_SERVICE    3
#define GSM48_MM_SST_NO_IMSI        4
#define GSM48_MM_SST_NO_CELL_AVAIL  5
#define GSM48_MM_SST_LOC_UPD_NEEDED 6
#define GSM48_MM_SST_PLMN_SEARCH    7
#define GSM48_MM_SST_PLMN_SEARCH_NORMAL 8
#define GSM48_MM_SST_RX_VGCS_NORMAL 9
#define GSM48_MM_SST_RX_VGCS_LIMITED    10

#endif
